language: python

services:
  - docker

before_install:
  - docker build --target development --tag todo-app:dev .
	- docker build --target production --tag todo-app:prod .
  - docker build --target test --tag todo-app:test .
  
script:
  - echo "yes"