--- 
before_install: 
  - "docker build --target development --tag todo-app:dev ."
  - "docker build --target test --tag todo-app:test ."
  - "docker run -it --rm --env-file todo_files/.env --env FLASK_ENV=test --mount type=bind,source=`pwd`/todo_files,target=/app/todo_files/ todo-app:test tests/unit_test.py"
language: python
script: 
  - "echo \"yes\""
services: 
  - docker
