--- 
before_install: 
  - "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
  - "docker build --target test --tag todo-app:test ."
  - "docker run -it --rm --env FLASK_ENV=test todo-app:test tests/unit_test.py"
language: python
python: 
  - 3.7
script: 
  - "echo \"yes\""
services: 
  - docker
